name: Test
on:
  push:
    branches:
      - master
jobs:
  macos:
    name: MacOS (x64)
    runs-on: macos-11
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build Native
        run: ./buildnative.sh
      - name: Build
        run: dotnet build Assembler.sln
      - name: Test
        run: dotnet test -l "console;verbosity=detailed" --no-build --nologo
  linux:
    name: Linux (x64)
    runs-on: ubuntu-18.04
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build
        run: dotnet build Assembler.sln
      - name: Test
        run: dotnet test -l "console;verbosity=detailed" --no-build --nologo
  windows:
    name: Windows (x64)
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build
        run: dotnet build Assembler.sln
      - name: Test
        run: dotnet test -l "console;verbosity=detailed" --no-build --nologo
  linux_arm64:
    name: Linux (arm64)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04
        run: uname -a