name: Test
on:
  push:
    branches:
      - master
jobs:
  macos:
    name: MacOS (x64)
    runs-on: macos-11
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build Native
        run: ./buildnative.sh
      - name: Build
        run: dotnet build Assembler.sln
      - name: Test
        run: dotnet test -l "console;verbosity=detailed" --no-build --nologo
  linux:
    name: Linux (x64)
    runs-on: ubuntu-18.04
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build
        run: dotnet build Assembler.sln
      - name: Test
        run: dotnet test -l "console;verbosity=detailed" --no-build --nologo
  windows:
    name: Windows (x64)
    runs-on: windows-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'
      - name: Restore Tools
        run: dotnet tool restore
      - name: Paket Restore
        run: dotnet paket restore
      - name: Build
        run: dotnet build Assembler.sln
      - name: Test
        run: dotnet test -l "console;verbosity=detailed" --no-build --nologo
  linux_arm64:
    name: Linux (arm64)
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04
          run: |
            apt-get update
            apt-get install -y wget
            wget https://download.visualstudio.microsoft.com/download/pr/ad60a07c-d4f0-4225-9154-c3a2ec0f34cf/a588cd2b94db2214f6e5dcd02c4aa37a/dotnet-sdk-6.0.200-linux-arm64.tar.gz
            tar -xf dotnet-sdk-6.0.200-linux-arm64.tar.gz
            ./dotnet-sdk-6.0.200-linux-arm64/dotnet tool restore
            ./dotnet-sdk-6.0.200-linux-arm64/dotnet build Assembler.sln
            ./dotnet-sdk-6.0.200-linux-arm64/dotnet test -l "console;verbosity=detailed" --no-build --nologo
